name: "ciya"
arch: "amd64"
platform: "linux"
version: "0.2.0"
section: "utils"
priority: "optional"
maintainer: "Johnryzon Z. Abejero, Nguyễn Phước Thành Lâm"
description: "A programming language made with care"
vendor: "Ciya-vm"
homepage: "https://ciya-vm.github.io"
license: "GPLv2"

contents:
  - src: "./build/ciya"
    dst: "/usr/local/bin/ciya"
    type: "file"
    file_info:
      mode: 0755
